function New-SEBVRageAuthHeaders {
    <#
    .SYNOPSIS
        Generates HMAC-SHA1 authentication headers for VRage Remote API requests.

    .DESCRIPTION
        Internal helper function that creates the authentication headers required
        by the VRage Remote API. The authentication scheme uses HMAC-SHA1 where:

        1. A random nonce is generated from cryptographic random bytes.
        2. The current UTC date is formatted in RFC1123 format.
        3. The security key (a Base64-encoded byte key generated by Torch) is
           Base64-DECODED to obtain the HMAC key bytes. Using the UTF-8 bytes of
           the key string instead produces a signature the server rejects.
        4. An HMAC-SHA1 signature is computed over the message, which is the
           request URI, nonce, and date, CRLF-separated and CRLF-terminated:
           "$RequestUri`r`n$Nonce`r`n$Date`r`n". Binding the signature to the
           resource prevents a captured Authorization header from being replayed
           against another endpoint.
        5. The Authorization header is set to "nonce:base64(signature)".

        This function is not exported and is intended for use only within the
        VRageAPI module.

        NOTE: the exact field order/separators are unverified against a live Torch
        server (see roadmap). Validate before relying on authenticated calls.

    .PARAMETER SecurityKey
        The Base64-encoded "Remote API" security key configured in the Torch
        server for VRage Remote API authentication (not a plaintext password).

    .PARAMETER RequestUri
        The absolute request path the signature is bound to, e.g.
        '/vrageremote/v1/session/save'. Mandatory -- the signature is
        resource-bound, so the URI being signed must be supplied.

    .PARAMETER Nonce
        Optional nonce override for deterministic testing. Generated from
        cryptographic random bytes when omitted.

    .PARAMETER Date
        Optional RFC1123 date override for deterministic testing. Set to the
        current UTC time when omitted.

    .OUTPUTS
        System.Collections.Hashtable
        A hashtable containing 'Date' and 'Authorization' header values, plus
        the 'Nonce' used for the request.

    .EXAMPLE
        $headers = New-SEBVRageAuthHeaders -SecurityKey $base64Key -RequestUri '/vrageremote/v1/session/save'
        # Returns: @{ Date = 'Thu, 27 Feb 2026 12:00:00 GMT'; Authorization = 'a1b2c3...:base64sig'; Nonce = 'a1b2c3...' }
    #>
    [CmdletBinding()]
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$SecurityKey,

        # The absolute request path being signed, e.g. '/vrageremote/v1/session/save'.
        # The VRage scheme binds the signature to the resource, so this must be included.
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$RequestUri,

        # Optional overrides for deterministic testing; generated when omitted.
        [Parameter()]
        [string]$Nonce,

        [Parameter()]
        [string]$Date
    )

    # Generate random nonce from cryptographic random bytes (unless supplied for testing).
    if ([string]::IsNullOrEmpty($Nonce)) {
        $nonceBytes = [byte[]]::new(16)
        [System.Security.Cryptography.RandomNumberGenerator]::Fill($nonceBytes)
        $Nonce = ($nonceBytes | ForEach-Object { $_.ToString('x2') }) -join ''
    }

    # Current UTC date in RFC1123 format (unless supplied for testing).
    if ([string]::IsNullOrEmpty($Date)) {
        $Date = [DateTime]::UtcNow.ToString('R')
    }

    # The VRage Remote API key is a Base64-encoded byte key generated by Torch -- it must be
    # Base64-decoded to obtain the HMAC key bytes (using the UTF-8 bytes of the key string
    # produces a signature the server rejects).
    try {
        $keyBytes = [Convert]::FromBase64String($SecurityKey)
    }
    catch {
        throw "VRage security_key is not valid Base64. Use the Base64 'Remote API' key from the Torch config, not a plaintext password."
    }

    # Message is the request URI, nonce, and date, newline-separated. The signature is bound
    # to the resource so a captured Authorization header cannot be replayed against another
    # endpoint. NOTE: validate the exact field order against your Torch/VRage version.
    $message = "$RequestUri`r`n$Nonce`r`n$Date`r`n"
    $messageBytes = [System.Text.Encoding]::UTF8.GetBytes($message)

    $hmacSha1 = [System.Security.Cryptography.HMACSHA1]::new($keyBytes)
    try {
        $hashBytes = $hmacSha1.ComputeHash($messageBytes)
    }
    finally {
        $hmacSha1.Dispose()
    }

    $signature = [Convert]::ToBase64String($hashBytes)

    return @{
        Date          = $Date
        Authorization = "${Nonce}:${signature}"
        Nonce         = $Nonce
    }
}
