function New-SEBVRageAuthHeaders {
    <#
    .SYNOPSIS
        Generates HMAC-SHA1 authentication headers for VRage Remote API requests.

    .DESCRIPTION
        Internal helper function that creates the authentication headers required
        by the VRage Remote API. The authentication scheme uses HMAC-SHA1 where:

        1. A random nonce is generated from cryptographic random bytes.
        2. The current UTC date is formatted in RFC1123 format.
        3. An HMAC-SHA1 signature is computed over the message (nonce + date)
           using the security key converted to UTF-8 bytes.
        4. The Authorization header is set to "nonce:base64(signature)".

        This function is not exported and is intended for use only within the
        VRageAPI module.

    .PARAMETER SecurityKey
        The 8-character security key configured in the Torch server for VRage
        Remote API authentication.

    .OUTPUTS
        System.Collections.Hashtable
        A hashtable containing 'Date' and 'Authorization' header values, plus
        the 'Nonce' used for the request.

    .EXAMPLE
        $headers = New-SEBVRageAuthHeaders -SecurityKey 'MyKey123'
        # Returns: @{ Date = 'Thu, 27 Feb 2026 12:00:00 GMT'; Authorization = 'a1b2c3...:base64sig'; Nonce = 'a1b2c3...' }
    #>
    [CmdletBinding()]
    [OutputType([hashtable])]
    param(
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$SecurityKey,

        # The absolute request path being signed, e.g. '/vrageremote/v1/session/save'.
        # The VRage scheme binds the signature to the resource, so this must be included.
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$RequestUri,

        # Optional overrides for deterministic testing; generated when omitted.
        [Parameter()]
        [string]$Nonce,

        [Parameter()]
        [string]$Date
    )

    # Generate random nonce from cryptographic random bytes (unless supplied for testing).
    if ([string]::IsNullOrEmpty($Nonce)) {
        $nonceBytes = [byte[]]::new(16)
        [System.Security.Cryptography.RandomNumberGenerator]::Fill($nonceBytes)
        $Nonce = ($nonceBytes | ForEach-Object { $_.ToString('x2') }) -join ''
    }

    # Current UTC date in RFC1123 format (unless supplied for testing).
    if ([string]::IsNullOrEmpty($Date)) {
        $Date = [DateTime]::UtcNow.ToString('R')
    }

    # The VRage Remote API key is a Base64-encoded byte key generated by Torch -- it must be
    # Base64-decoded to obtain the HMAC key bytes (using the UTF-8 bytes of the key string
    # produces a signature the server rejects).
    try {
        $keyBytes = [Convert]::FromBase64String($SecurityKey)
    }
    catch {
        throw "VRage security_key is not valid Base64. Use the Base64 'Remote API' key from the Torch config, not a plaintext password."
    }

    # Message is the request URI, nonce, and date, newline-separated. The signature is bound
    # to the resource so a captured Authorization header cannot be replayed against another
    # endpoint. NOTE: validate the exact field order against your Torch/VRage version.
    $message = "$RequestUri`r`n$Nonce`r`n$Date`r`n"
    $messageBytes = [System.Text.Encoding]::UTF8.GetBytes($message)

    $hmacSha1 = [System.Security.Cryptography.HMACSHA1]::new($keyBytes)
    try {
        $hashBytes = $hmacSha1.ComputeHash($messageBytes)
    }
    finally {
        $hmacSha1.Dispose()
    }

    $signature = [Convert]::ToBase64String($hashBytes)

    return @{
        Date          = $Date
        Authorization = "${Nonce}:${signature}"
        Nonce         = $Nonce
    }
}
