#Requires -Module Pester

# Issue #14 -- reconcile the instance TOML schema to the keys the engine actually reads.
#
# Two incompatible instance schemas used to coexist: the generators wrote
# [paths]/[smb]/[vss]/[vrage_api].security_key with run_mode nested under [instance], while the
# documented example used [torch].world_path/[vrage_api].key/[backup]. NEITHER matched what the
# engine consumes at runtime. The engine reads FLAT top-level keys (world_path, staging_path,
# share_name, run_mode) plus a nested [vrage_api] table (port / security_key) -- see
# Invoke-SEBBackup, Invoke-SEBRestore, Test-SEBPreFlight, Start/Stop-SEBTorchServer.
#
# These tests pin that canonical contract:
#   1. The shipped example file parses and exposes exactly the canonical sections/keys, typed.
#   2. The string Register-Instance.ps1 generates parses to the canonical keys (top-level, not
#      buried under [instance]).
#   3. Get-SEBInstanceConfig returns a hashtable carrying every engine-read key (the full load
#      path, with the remote read mocked the way real PSRemoting deserializes a parsed config).
#   4. The back-compat shim maps a legacy [paths]/[smb]/[vss] config onto the canonical keys.
#
# PSToml is required to parse TOML. If it is absent the parsing contexts skip (and fail loudly
# under CI), mirroring Tests/SEBackup.Tests.ps1.

BeforeDiscovery {
    $script:psTomlAvailable = $null -ne (Get-Module -Name PSToml -ListAvailable -ErrorAction SilentlyContinue)
    if (-not $script:psTomlAvailable -and ($env:CI -match '^(true|1)$')) {
        throw 'PSToml is not installed. Install it before running the gate suite in CI (Install-Module PSToml -Force).'
    }
}

BeforeAll {
    $script:repoRoot = (Resolve-Path "$PSScriptRoot/../..").Path
    Import-Module "$script:repoRoot/SEBackup.psd1" -Force -DisableNameChecking 3>$null

    if (Get-Module -Name PSToml -ListAvailable -ErrorAction SilentlyContinue) {
        Import-Module PSToml -ErrorAction Stop
    }

    # An uninitialized PSSession satisfies the [PSSession] cast on -Session without a live
    # connection (the type has no public constructor). Every consumer of it is mocked.
    $script:fakeSession = [System.Runtime.Serialization.FormatterServices]::GetUninitializedObject(
        [System.Management.Automation.Runspaces.PSSession])

    # Mirror the exact instance TOML that Register-Instance.ps1 emits (canonical layout). Paths are
    # written with TOML-escaped backslashes ("\\"), just as the generator escapes them, so that
    # ConvertFrom-Toml parses them back to single-backslash Windows paths. Single-quoted here-string
    # so nothing (incl. the literal $ in the share name) is interpolated.
    $script:generatedToml = @'
# SEBackup Instance Configuration: PvPArena
# Generated by Register-Instance.ps1 on 2026-01-01 00:00:00

# --- Operational keys read by the backup/restore engine (must stay top-level) ---
run_mode     = "service"
world_path   = "C:\\TorchServers\\PvPArena\\Instance\\Saves\\PvPWorld"
staging_path = "D:\\SEBackup\\staging\\PvPArena"
share_name   = "SEBackup_PvPArena$"

[instance]
name         = "PvPArena"
display_name = "PvPArena"

[vrage_api]
port         = 8080
security_key = "abc123"

# Informational paths discovered during registration (not required by the engine).
[torch]
install_path = "C:\\TorchServers\\PvPArena"
data_root    = "C:\\TorchServers\\PvPArena\\Instance"
'@
}

Describe 'Instance TOML canonical schema (Issue #14)' {

    Context 'Shipped example file (NodeAgent/instance.example.toml)' -Skip:(-not $script:psTomlAvailable) {
        BeforeAll {
            $examplePath = Join-Path $script:repoRoot 'NodeAgent/instance.example.toml'
            $script:example = ConvertFrom-Toml -InputObject (Get-Content -Path $examplePath -Raw)
        }

        It 'parses to a dictionary' {
            $script:example | Should -Not -BeNullOrEmpty
            $script:example -is [System.Collections.IDictionary] | Should -BeTrue
        }

        It 'exposes operational keys at the TOP LEVEL (not nested under [instance])' {
            # This is the whole point of #14: a bare key after a [section] header would land in
            # that section. These must be root-level so the engine's $config['world_path'] works.
            $script:example.Keys | Should -Contain 'world_path'
            $script:example.Keys | Should -Contain 'staging_path'
            $script:example.Keys | Should -Contain 'share_name'
            $script:example.Keys | Should -Contain 'run_mode'
        }

        It 'world_path is a non-empty absolute Windows path' {
            $script:example['world_path'] | Should -BeOfType [string]
            $script:example['world_path'] | Should -Match '^[A-Za-z]:\\'
        }

        It 'run_mode is service or console' {
            $script:example['run_mode'] | Should -BeIn @('service', 'console')
        }

        It 'has a nested [vrage_api] table with port (int) and security_key' {
            $script:example['vrage_api'] | Should -Not -BeNullOrEmpty
            $script:example['vrage_api']['port'] | Should -BeOfType [long]
            # The engine reads security_key, NOT key.
            $script:example['vrage_api'].Keys | Should -Contain 'security_key'
            $script:example['vrage_api'].Keys | Should -Not -Contain 'key'
        }

        It 'has a nested [instance] table with name' {
            $script:example['instance']['name'] | Should -Not -BeNullOrEmpty
        }

        It 'does NOT use the superseded legacy sections at the active level' {
            # Legacy operational containers must not be the source of truth anymore.
            $script:example.Keys | Should -Not -Contain 'paths'
            $script:example.Keys | Should -Not -Contain 'smb'
        }
    }

    Context 'Register-Instance.ps1 generated config' -Skip:(-not $script:psTomlAvailable) {
        BeforeAll {
            $script:gen = ConvertFrom-Toml -InputObject $script:generatedToml
        }

        It 'puts world_path / staging_path / share_name / run_mode at the top level' {
            $script:gen['world_path']   | Should -Be 'C:\TorchServers\PvPArena\Instance\Saves\PvPWorld'
            $script:gen['staging_path'] | Should -Be 'D:\SEBackup\staging\PvPArena'
            $script:gen['share_name']   | Should -Be 'SEBackup_PvPArena$'
            $script:gen['run_mode']     | Should -Be 'service'
        }

        It 'nests port and security_key under [vrage_api]' {
            $script:gen['vrage_api']['port'] | Should -Be 8080
            $script:gen['vrage_api']['security_key'] | Should -Be 'abc123'
        }

        It 'keeps install paths as informational [torch] (not where the engine reads world_path)' {
            $script:gen['torch']['install_path'] | Should -Be 'C:\TorchServers\PvPArena'
            # world_path is top-level, NOT torch.world_path.
            $script:gen['torch'].Keys | Should -Not -Contain 'world_path'
        }
    }

    Context 'Get-SEBInstanceConfig full load path (remote read mocked)' -Skip:(-not $script:psTomlAvailable) {
        BeforeAll {
            Mock Get-SEBGlobalConfig -ModuleName ConfigManager {
                @{
                    defaults = @{
                        vrage_api = @{ port = 8080; save_timeout_seconds = 120 }
                        vss       = @{ mount_base = 'C:\SEBackup\vss_mount' }
                    }
                    compression    = @{ engine = 'auto'; level_7zip = 5 }
                    load_awareness = @{ enabled = $false }
                    network        = @{ max_bandwidth_mbps = 0 }
                }
            }

            # Real PSRemoting hands a parsed TOML config back as a deserialized object tree
            # (PSCustomObject for tables). Return that shape so Convert-PSObjectToHashtable's
            # PSCustomObject branch runs, exactly as in production.
            Mock Invoke-Command -ModuleName ConfigManager {
                [PSCustomObject]@{
                    run_mode     = 'service'
                    world_path   = 'C:\TorchServers\PvPArena\Instance\Saves\PvPWorld'
                    staging_path = 'D:\SEBackup\staging\PvPArena'
                    share_name   = 'SEBackup_PvPArena$'
                    instance     = [PSCustomObject]@{ name = 'PvPArena'; display_name = 'PvP' }
                    vrage_api    = [PSCustomObject]@{ port = 8080; security_key = 'abc123'; save_timeout_seconds = 180 }
                }
            }
        }

        It 'returns a hashtable' {
            $cfg = Get-SEBInstanceConfig -Session $script:fakeSession -InstanceName 'PvPArena'
            $cfg | Should -BeOfType [hashtable]
        }

        It 'carries every engine-read key, correctly typed' {
            $cfg = Get-SEBInstanceConfig -Session $script:fakeSession -InstanceName 'PvPArena'

            # Flat operational keys (Invoke-SEBBackup / Invoke-SEBRestore / Test-SEBPreFlight).
            $cfg['world_path']   | Should -Be 'C:\TorchServers\PvPArena\Instance\Saves\PvPWorld'
            $cfg['staging_path'] | Should -Be 'D:\SEBackup\staging\PvPArena'
            $cfg['share_name']   | Should -Be 'SEBackup_PvPArena$'
            $cfg['run_mode']     | Should -Be 'service'

            # Nested vrage_api (Save-SEBVRageWorld trigger + Start/Stop-SEBTorchServer).
            $cfg['vrage_api'] | Should -BeOfType [hashtable]
            [int]$cfg['vrage_api']['port'] | Should -Be 8080
            $cfg['vrage_api']['security_key'] | Should -Be 'abc123'
            [int]$cfg['vrage_api']['save_timeout_seconds'] | Should -Be 180
        }

        It 'attaches _InstanceName and _NodeName metadata' {
            $cfg = Get-SEBInstanceConfig -Session $script:fakeSession -InstanceName 'PvPArena'
            $cfg['_InstanceName'] | Should -Be 'PvPArena'
            $cfg.ContainsKey('_NodeName') | Should -BeTrue
        }

        It 'ContainsKey works on the merged result (it is a real hashtable, not an OrderedDictionary)' {
            # Get-SEBBackupType-style call sites use .ContainsKey(); PSToml returns an
            # OrderedDictionary that lacks the method, so the converter MUST normalize it.
            $cfg = Get-SEBInstanceConfig -Session $script:fakeSession -InstanceName 'PvPArena'
            { $cfg.ContainsKey('world_path') } | Should -Not -Throw
            $cfg.ContainsKey('world_path') | Should -BeTrue
        }
    }

    Context 'Test-SEBConfig validates the canonical example' -Skip:(-not $script:psTomlAvailable) {
        It 'reports the shipped example as valid' {
            # Closes the loop: the validator and the documented example must agree on the schema.
            $examplePath = Join-Path $script:repoRoot 'NodeAgent/instance.example.toml'
            $result = Test-SEBConfig -Type Instance -Path $examplePath
            $result.IsValid | Should -BeTrue -Because "validator errors: $($result.Errors -join '; ')"
        }

        It 'flags a legacy [vrage_api].key as the wrong field name' {
            # The example uses security_key; if someone hand-writes the legacy "key", the validator
            # should steer them to security_key (what the engine reads) rather than pass silently.
            $legacy = @{
                world_path = 'C:\W\Saves\X'
                share_name = 'SEBackup_X$'
                instance   = @{ name = 'X'; display_name = 'X' }
                vrage_api  = @{ port = 8080; key = 'legacy' }
            }
            $result = Test-SEBConfig -Type Instance -Config $legacy
            ($result.Warnings -join ' ') | Should -Match 'security_key'
        }
    }

    Context 'Test-SEBConfig -Config parity with the engine (Issue #14 review)' {

        # (a) The ByConfig path must validate exactly what Get-SEBInstanceConfig accepts. A caller
        # who hands in ConvertFrom-Toml output gets a config whose nested tables are
        # OrderedDictionary (the [hashtable] cast on -Config coerces only the TOP level). Without the
        # deep normalization in Test-SEBConfig, "$Config.vrage_api -is [hashtable]" is false and
        # [vrage_api] validation is silently skipped. These tests prove it actually runs.
        Context 'ByConfig with OrderedDictionary children (ConvertFrom-Toml output)' -Skip:(-not $script:psTomlAvailable) {
            It 'validates the [vrage_api] table -- an invalid port is an ERROR' {
                $cfg = ConvertFrom-Toml -InputObject $script:generatedToml
                $cfg['vrage_api']['port'] = 70000   # out of range
                $result = Test-SEBConfig -Type Instance -Config $cfg
                $result.IsValid | Should -BeFalse
                ($result.Errors -join ' ') | Should -Match 'vrage_api.*port'
            }

            It 'reports a valid ConvertFrom-Toml config (nested OrderedDictionary) as valid' {
                $cfg = ConvertFrom-Toml -InputObject $script:generatedToml
                $result = Test-SEBConfig -Type Instance -Config $cfg
                $result.IsValid | Should -BeTrue -Because "validator errors: $($result.Errors -join '; ')"
            }
        }

        # (b) A legacy [paths]/[smb] config is what the engine STILL accepts (Get-SEBInstanceConfig
        # normalizes it). The validator must therefore accept it too: migration WARNINGS, never hard
        # "world_path/share_name missing" ERRORS.
        It 'accepts a legacy [paths]/[smb] config with WARNINGS, not ERRORS' {
            $legacy = @{
                instance  = @{ name = 'Legacy'; display_name = 'Legacy'; run_mode = 'console' }
                paths     = @{ world_save = 'C:\TorchServers\Legacy\Saves\W'; staging_local = 'E:\stage\Legacy' }
                smb       = @{ share_name = 'SEBackup_Legacy$' }
                vrage_api = @{ port = 8081; key = 'legacykey' }
            }
            $result = Test-SEBConfig -Type Instance -Config $legacy

            $result.IsValid | Should -BeTrue -Because "validator errors: $($result.Errors -join '; ')"
            $result.Errors.Count | Should -Be 0
            # The migration nudges for each legacy section must surface.
            ($result.Warnings -join ' ') | Should -Match 'world_save'
            ($result.Warnings -join ' ') | Should -Match 'share_name'
            ($result.Warnings -join ' ') | Should -Match 'staging_local'
        }

        It 'does not mutate the caller hashtable passed to -Config' {
            # The shim is non-destructive; Test-SEBConfig must not promote legacy keys onto the
            # caller's object.
            $legacy = @{
                instance  = @{ name = 'Legacy'; run_mode = 'console' }
                paths     = @{ world_save = 'C:\W\Saves\L'; staging_local = 'E:\stage\L' }
                smb       = @{ share_name = 'SEBackup_L$' }
                vrage_api = @{ port = 8081; key = 'legacykey' }
            }
            $null = Test-SEBConfig -Type Instance -Config $legacy

            $legacy.ContainsKey('world_path') | Should -BeFalse
            $legacy.ContainsKey('share_name') | Should -BeFalse
            $legacy['vrage_api'].ContainsKey('security_key') | Should -BeFalse
        }

        It 'requires service_name to be a non-empty string when present' {
            $cfg = @{
                instance     = @{ name = 'X'; display_name = 'X' }
                world_path   = 'C:\W\Saves\X'
                staging_path = 'D:\stage\X'
                share_name   = 'SEBackup_X$'
                service_name = ''   # empty would silently override the engine default
                vrage_api    = @{ port = 8080; security_key = 'k' }
            }
            $result = Test-SEBConfig -Type Instance -Config $cfg
            $result.IsValid | Should -BeFalse
            ($result.Errors -join ' ') | Should -Match 'service_name'
        }

        It 'accepts valid service_name and process_name without warnings about them' {
            $cfg = @{
                instance     = @{ name = 'X'; display_name = 'X' }
                world_path   = 'C:\W\Saves\X'
                staging_path = 'D:\stage\X'
                share_name   = 'SEBackup_X$'
                service_name = 'TorchServer_X'
                process_name = 'Torch.Server'
                vrage_api    = @{ port = 8080; security_key = 'k' }
            }
            $result = Test-SEBConfig -Type Instance -Config $cfg
            $result.IsValid | Should -BeTrue -Because "validator errors: $($result.Errors -join '; ')"
            ($result.Warnings -join ' ') | Should -Not -Match 'service_name'
            ($result.Warnings -join ' ') | Should -Not -Match 'process_name'
        }
    }

    # (c) The canonical shim itself must be non-destructive. Exercised directly in module scope
    # (it is a Private function) so a regression in the cloning is caught even if the Test-SEBConfig
    # wiring changes.
    Context 'ConvertTo-CanonicalInstanceConfig is non-destructive (Private helper)' {
        It 'leaves the input hashtable unchanged while returning a normalized copy' {
            $result = InModuleScope ConfigManager {
                $source = @{
                    instance  = @{ name = 'L'; run_mode = 'console' }
                    paths     = @{ world_save = 'C:\W\Saves\L'; staging_local = 'E:\stage\L' }
                    smb       = @{ share_name = 'SEBackup_L$' }
                    vrage_api = @{ port = 8081; key = 'legacykey' }
                }
                $out = ConvertTo-CanonicalInstanceConfig -InputObject $source

                [PSCustomObject]@{
                    InputUntouchedTop   = (-not $source.ContainsKey('world_path')) -and (-not $source.ContainsKey('share_name'))
                    InputUntouchedVrage = -not $source['vrage_api'].ContainsKey('security_key')
                    OutWorldPath        = $out['world_path']
                    OutShareName        = $out['share_name']
                    OutStagingPath      = $out['staging_path']
                    OutRunMode          = $out['run_mode']
                    OutSecurityKey      = $out['vrage_api']['security_key']
                    DifferentReference  = -not [object]::ReferenceEquals($source, $out)
                }
            }

            $result.InputUntouchedTop   | Should -BeTrue
            $result.InputUntouchedVrage | Should -BeTrue
            $result.DifferentReference  | Should -BeTrue
            # And the returned copy is fully normalized to the canonical keys.
            $result.OutWorldPath   | Should -Be 'C:\W\Saves\L'
            $result.OutShareName   | Should -Be 'SEBackup_L$'
            $result.OutStagingPath | Should -Be 'E:\stage\L'
            $result.OutRunMode     | Should -Be 'console'
            $result.OutSecurityKey | Should -Be 'legacykey'
        }

        It 'returns the SAME reference for an already-canonical config (fast path, no copy)' {
            $isSameRef = InModuleScope ConfigManager {
                $canon = @{
                    world_path = 'C:\W\Saves\X'
                    share_name = 'SEBackup_X$'
                    vrage_api  = @{ port = 8080; security_key = 'k' }
                }
                $out = ConvertTo-CanonicalInstanceConfig -InputObject $canon
                [object]::ReferenceEquals($canon, $out)
            }
            $isSameRef | Should -BeTrue
        }
    }

    Context 'Back-compat shim normalizes a legacy instance config' -Skip:(-not $script:psTomlAvailable) {
        BeforeAll {
            Mock Get-SEBGlobalConfig -ModuleName ConfigManager {
                @{ defaults = @{ vrage_api = @{ port = 8080 } } }
            }

            # The shape an OLD node still has on disk: operational values under [paths]/[smb]/[vss],
            # run_mode under [instance], and the VRage key named 'key'. Returned as PSCustomObject to
            # mimic remoting.
            Mock Invoke-Command -ModuleName ConfigManager {
                [PSCustomObject]@{
                    instance  = [PSCustomObject]@{ name = 'Legacy'; display_name = 'Legacy'; run_mode = 'console' }
                    paths     = [PSCustomObject]@{
                        torch_install = 'C:\TorchServers\Legacy'
                        world_save    = 'C:\TorchServers\Legacy\Instance\Saves\W'
                        staging_local = 'E:\stage\Legacy'
                    }
                    smb       = [PSCustomObject]@{ share_name = 'SEBackup_Legacy$' }
                    vrage_api = [PSCustomObject]@{ port = 8081; key = 'legacykey' }
                    vss       = [PSCustomObject]@{ volume = 'C:\' }
                }
            }
        }

        It 'maps legacy nested values onto the canonical top-level keys the engine reads' {
            $cfg = Get-SEBInstanceConfig -Session $script:fakeSession -InstanceName 'Legacy'

            $cfg['world_path']   | Should -Be 'C:\TorchServers\Legacy\Instance\Saves\W'
            $cfg['staging_path'] | Should -Be 'E:\stage\Legacy'
            $cfg['share_name']   | Should -Be 'SEBackup_Legacy$'
            $cfg['run_mode']     | Should -Be 'console'
            # [vrage_api].key -> [vrage_api].security_key
            $cfg['vrage_api']['security_key'] | Should -Be 'legacykey'
        }
    }
}
